var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var jade_settings={},jade_css_suffix="",jade_panels=["panel_home","panel_examples"],jade_panel_labels=["Home","Examples","Output"],jade_code_panels=[],jade_panel_stack=["panel_home"],Jade=function(){};
Jade.load_gist=function(a){var b,c,d,e,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:return g.setCatchFinallyBlocks(2),g.yield(fetch("https://api.github.com/gists/"+a+"?"+new Date),4);case 4:return b=g.yieldResult,g.yield(b.json(),5);case 5:c=g.yieldResult;d=$jscomp.makeIterator(Object.values(c.files));for(e=d.next();!e.done;e=d.next())f=e.value,Jade.incorporate_code(f.content);auto_exec();Jade.incorporate_code("auto_exec=null");g.leaveTryBlock(0);break;
case 2:g.enterCatchBlock(),g.jumpToEnd()}})};
Jade.import_code_module=function(a){var b,c,d,e,f,g,h,k,l,m,p,r,t,q,u;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){switch(n.nextAddress){case 1:jade_settings.workbook.module_to_import=a;Jade.hide_element("import-module");Jade.save_settings();if(!a)return n["return"]();b=null;"http"===a.substr(0,4)?a.toLowerCase().includes("gist.github.com")?(a.split("/"),b="https://api.github.com/gists/"+d[d.length-1]+"?"+new Date):b=a:b="https://api.github.com/gists/"+a+"?"+new Date;n.setCatchFinallyBlocks(2);
return n.yield(fetch(b),4);case 4:return c=n.yieldResult,n.yield(c.text(),5);case 5:d=n.yieldResult;n.leaveTryBlock(3);break;case 2:return e=n.enterCatchBlock(),alert(e.message,"Error Loading Module"),console.log("Error fetching gist",e),n["return"]();case 3:f=[];try{g=JSON.parse(d);try{for(h=$jscomp.makeIterator(Object.values(g.files)),k=h.next();!k.done;k=h.next())l=k.value,f.push({name:l.filename.split(".js")[0],code:l.content})}catch(v){return alert(v.message,"Error Parsing Gist"),n["return"]()}}catch(v){m=
null;if(d.includes("ace.module:"))try{m=JSON.parse(d.split("ace.module:")[1].split("*/")[0]).name}catch(w){p=b.split("/"),m=p[p.length-1]}if(!m){for(r=1;tag(Jade.panel_label_to_panel_name("Code "+r));)r++;f.push({name:"Code "+r,code:d})}}t=$jscomp.makeIterator(f);for(k=t.next();!k.done;k=t.next())q=k.value,tag(Jade.panel_label_to_panel_name(q.name+" Module"))?(u=ace.edit(Jade.panel_label_to_panel_name(q.name)+"_module-content"),u.setValue(q.code)):Jade.add_code_module(q.name,q.code);n.jumpToEnd()}})};
Jade.set_css=function(a){jade_css_suffix=a};Jade.add_library=function(a){var b=document.createElement("script");b.setAttribute("src",a);document.head.appendChild(b)};Jade.close_canvas=function(){jade_panel_stack.pop();Jade.show_panel(jade_panel_stack.pop())};Jade.open_editor=function(){Jade.show_panel(jade_code_panels[0])};Jade.open_output=function(){Jade.show_panel("panel_output")};Jade.open_automations=function(a){Jade.show_automations(a)};Jade.reset=function(){Jade.show_panel("panel_home")};
Jade.open_canvas=function(a,b,c,d){d&&Jade.set_style(d);tag(a)||Jade.build_panel(a);jade_panels.includes(a)||jade_panels.push(a);Jade.show_panel(a);b&&(c||void 0===c?tag(a).innerHTML=Jade.panel_close_button(a)+b:tag(a).innerHTML=b)};
Jade.print=function(a,b){tag("panel_output").lastChild.lastChild.firstChild.tagName||b||(b="");if(b){var c=document.createElement("div");c.className="jade-output";var d=document.createElement("div");d.className="jade-output-header";var e=new Date,f=" am",g=e.getHours();11<g&&(f="pm",12<g&&(g-=12));d.innerHTML='<span class="jade-output-time">'+g+":"+("0"+e.getMinutes()).slice(-2)+":"+("0"+e.getSeconds()).slice(-2)+f+"</span> "+b+'<div class="jade-output-close"><i class="fas fa-times" style="color:white;margin-right:.3rem;cursor:pointer" onclick="this.parentNode.parentNode.parentNode.remove()"></div>';
e=document.createElement("div");e.className="jade-output-body";e.innerHTML='<div style="margin:0;font-family: monospace;">'+a.replaceAll("\n","<br />")+"<br /></div>";c.appendChild(d);c.appendChild(e);tag("panel_output").appendChild(c)}else tag("panel_output").lastChild.lastChild.firstChild.innerHTML+=a.replaceAll("\n","<br />")+"<br />"};Jade.open_examples=function(){Jade.set_style();Jade.show_panel("panel_examples")};Jade.set_theme=function(a){Jade.set_style(a)};
Jade.list_themes=function(){for(var a=$jscomp.makeIterator(Object.entries(jade_settings.workbook.styles)),b=a.next();!b.done;b=a.next())b=$jscomp.makeIterator(b.value),b.next(),b.next()};
Jade.officeReady=function(a){a.host===Office.HostType.Excel?Excel.run(function(b){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return c=b.workbook.settings.getItemOrNullObject("jade").load("value"),d.yield(b.sync(),2);c.isNullObject?(jade_settings.user={ace_options:{selectionStyle:"line",highlightActiveLine:!0,highlightSelectedWord:!0,readOnly:!1,copyWithEmptySelection:!1,cursorStyle:"ace",mergeUndoDeltas:!0,behavioursEnabled:!0,wrapBehavioursEnabled:!0,
enableAutoIndent:!0,showLineNumbers:!0,hScrollBarAlwaysVisible:!1,vScrollBarAlwaysVisible:!1,highlightGutterLine:!0,animatedScroll:!1,showInvisibles:!1,showPrintMargin:!1,printMarginColumn:80,printMargin:80,fadeFoldWidgets:!1,showFoldWidgets:!0,displayIndentGuides:!0,showGutter:!0,fontSize:"14pt",scrollPastEnd:0,theme:"ace/theme/tomorrow",maxPixelHeight:0,useTextareaForIME:!0,scrollSpeed:2,dragDelay:0,dragEnabled:!0,focusTimeout:0,tooltipFollowsMouse:!0,firstLineNumber:1,overwrite:!1,newLineMode:"auto",
useWorker:!1,navigateWithinSoftTabs:!1,wrap:!0,indentedSoftWrap:!0,foldStyle:"markbegin",mode:"ace/mode/javascript",enableMultiselect:!0,enableBlockSelect:!0,tabSize:2,useSoftTabs:!0}},jade_settings.workbook={code_module_ids:[],examples_gist_id:"904983747625c3fdc8dfa69e0aaa0f08",styles:{system:null,none:"/*No Theme CSS Used*/",mvp:"https://cdnjs.cloudflare.com/ajax/libs/mvp.css/1.8.0/mvp.css",marx:"https://cdnjs.cloudflare.com/ajax/libs/marx/4.0.0/marx.min.css",water:"https://cdn.jsdelivr.net/npm/water.css@2/out/water.css",
"dark water":"https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css",sajura:"https://unpkg.com/sakura.css/css/sakura.css",tacit:"https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.5.5.min.css",pure:"https://unpkg.com/purecss@2.0.6/build/pure-min.css",picnic:"https://cdn.jsdelivr.net/npm/picnic",wing:"https://unpkg.com/wingcss",chota:"https://unpkg.com/chota@latest",bootstrap:"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"}}):(jade_settings.workbook=c.value.workbook,
jade_settings.user=c.value.user);Jade.configure_settings();Jade.start_me_up();d.jumpToEnd()})}):(document.getElementById("sideload-msg").style.display="flex",document.getElementById("menu").style.display="none")};
Jade.start_me_up=function(){jade_settings.workbook.styles.system=tag("head_style").innerText;jade_panels.push("panel_home");jade_settings.workbook.load_gist_id&&Jade.load_gist(jade_settings.workbook.load_gist_id);tag("new-module-name").addEventListener("keyup",function(a){a.preventDefault();"Enter"===a.key&&tag("module-add-button").click()});tag("gist-url").addEventListener("keyup",function(a){a.preventDefault();"Enter"===a.key&&tag("module-import-button").click()});window.addEventListener("resize",
function(a){a=$jscomp.makeIterator(jade_code_panels);for(var b=a.next();!b.done;b=a.next())tag(b.value+"_editor-page").style.height=Jade.editor_height()},!0);Jade.init_examples();Jade.init_output();0<jade_settings.workbook.code_module_ids.length&&Jade.show_element("open-editor");Excel.run(function(a){var b,c,d,e,f,g,h,k,l,m;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){1==p.nextAddress&&(b=new DOMParser,c=$jscomp.makeIterator(jade_settings.workbook.code_module_ids),d=c.next());if(5!=
p.nextAddress){if(d.done)return p.jumpTo(0);e=d.value;f=a.workbook.customXmlParts.getItem(e);g=f.getXml();return p.yield(a.sync(),5)}h=b.parseFromString(g.value,"application/xml");k=h.getElementsByTagName("name")[0].textContent;l=atob(h.getElementsByTagName("code")[0].textContent);m=atob(h.getElementsByTagName("options")[0].textContent);Jade.add_code_editor(k,l,e,null,JSON.parse(m));d=c.next();return p.jumpTo(2)})})};
Jade.configure_settings=function(){tag("jade-font-size").value=jade_settings.user.ace_options.fontSize.replace("pt","");!1===jade_settings.user.ace_options.wrap?tag("jade-word-wrap").value="no-wrap":jade_settings.user.ace_options.indentedSoftWrap?tag("jade-word-wrap").value="wrap-indented":tag("jade-word-wrap").value="wrap";tag("examples-gist-id").value=jade_settings.workbook.examples_gist_id;tag("jade-theme").value=jade_settings.user.ace_options.theme.split("/")[2];tag("jade-line-numbers").checked=
jade_settings.user.ace_options.showGutter;jade_settings.workbook.load_gist_id&&(tag("load-gist-id").value=jade_settings.workbook.load_gist_id)};
Jade.save_settings=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress){tag("examples-gist-id").value&&jade_settings.workbook.examples_gist_id!==tag("examples-gist-id").value&&Jade.rebuild_examples(tag("examples-gist-id").value);jade_settings.workbook.examples_gist_id=tag("examples-gist-id").value;jade_settings.workbook.load_gist_id=tag("load-gist-id").value;jade_settings.user.ace_options.theme="ace/theme/"+tag("jade-theme").value;jade_settings.user.ace_options.fontSize=
tag("jade-font-size").value+"pt";jade_settings.user.ace_options.showGutter=tag("jade-line-numbers").checked;switch(tag("jade-word-wrap").value){case "wrap":jade_settings.user.ace_options.wrap=!0;jade_settings.user.ace_options.indentedSoftWrap=!1;break;case "wrap-indented":jade_settings.user.ace_options.wrap=!0;jade_settings.user.ace_options.indentedSoftWrap=!0;break;default:jade_settings.user.ace_options.wrap="off"}Jade.apply_editor_options(jade_settings.user.ace_options);return a.yield(Jade.write_settings_to_workbook(),
2)}Jade.hide_element("settings-page");a.jumpToEnd()})};Jade.write_settings_to_workbook=function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){return a.yield(Excel.run(function(b){var c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){c=b.workbook.settings;c.add("jade",jade_settings);return d.yield(b.sync(),0)})}),0)})};Jade.apply_editor_options=function(a){for(var b=$jscomp.makeIterator(jade_code_panels),c=b.next();!c.done;c=b.next())ace.edit(c.value+"-content").setOptions(a)};
Jade.submit_feedback=function(){var a,b,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){switch(e.nextAddress){case 1:a=[];""===tag("fb-type").value&&a.push("<li>You must indicate the <b>type</b> of your feedback.</li>");""===tag("fb-text").value&&a.push("<li>You must provide the <b>text</b> of your feedback.</li>");""===tag("fb-platform").value&&a.push("<li>You must provide the <b>platform</b> you are using.</li>");if(0!==a.length){tag("fb-message").style.color="red";tag("fb-message").innerHTML=
"<ul>"+a.join("")+"</ul>";tag("fb-message").scrollIntoView(!0);e.jumpTo(0);break}b=[];b.push("entry.1033992853=");b.push(encodeURIComponent(tag("fb-type").value));b.push("&entry.482647522=");b.push(encodeURIComponent(tag("fb-platform").value));b.push("&entry.1230850697=");b.push(encodeURIComponent(tag("fb-email").value));b.push("&entry.1009690762=");b.push(encodeURIComponent(tag("fb-text").value));b.push("&entry.64124153=");b.push(encodeURIComponent("Addin"));tag("fb-message").innerHTML="";c={method:"POST",
mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b.join("")};e.setCatchFinallyBlocks(3);return e.yield(fetch("https://docs.google.com/forms/u/0/d/e/1FAIpQLSeRCZKHMU0HvXEiia8dn6hL0DfGoAH-PCJZolfiN1S_O90eSQ/formResponse",c),5);case 5:return d=e.yieldResult,e.yield(d.text(),6);case 6:tag("fb-message").style.color="green";switch(tag("fb-type").value){case "Feature Resuest":a.push("Thanks for your feedback. Were not sure when we'll be updaing next but thanks for helping us understand your needs.");
break;case "Report Issue":a.push("Thanks for reporing this issue. While we cannot respond to every problem report, we'll do what we can.");break;case "Offer to help with development":a.push("Thanks for offering to help on this project.  We'll take a look at your comment and get back to you--if you provided a valid email address.");break;case "Praise for Addin":a.push("Thanks a million. We thrive on positive feedback!");break;default:a.push("Thanks for asking this question. While we cannot respond to every question, we'll do what we can.")}tag("fb-message").innerHTML=
a.join("");tag("fb-message").scrollIntoView(!0);setTimeout(function(){Jade.hide_element("survey");tag("fb-message").innerHTML=""},1E4);e.leaveTryBlock(0);break;case 3:e.enterCatchBlock(),tag("fb-message").style.color="red",tag("fb-message").innerHTML='Oops.  It looks as though there was a network error.  Your can tray again later or submit at our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeRCZKHMU0HvXEiia8dn6hL0DfGoAH-PCJZolfiN1S_O90eSQ/viewform?usp=pp_url&entry.64124153=web" target="_blank">Google Form<a>.',
window.scrollTo(0,document.body.scrollHeight),tag("fb-message").scrollIntoView(!0),e.jumpToEnd()}})};
Jade.add_code_module=function(a,b){a||(a="code");for(var c=$jscomp.makeIterator(jade_code_panels),d=c.next();!d.done;d=c.next())if(d.value===Jade.panel_label_to_panel_name(a)+"_module"){alert('A module named "'+a+'" already exists in this workbook.  <br><br>Choose a differnt name.',"Invalid Module Name");return}b||(b=0===jade_code_panels.length?Jade.default_code():Jade.default_code("panel_"+a.toLowerCase().split(" ").join("_")+"_module"));Jade.add_code_editor(a,b,"");Jade.hide_element("add-module");
Jade.show_element("open-editor");Jade.show_panel(jade_code_panels[jade_code_panels.length-1]);Jade.write_module_to_workbook(b,jade_code_panels[jade_code_panels.length-1])};
Jade.get_style=function(a,b,c){var d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return void 0===c&&(c=!0),jade_settings.workbook.styles[a]||(jade_settings.workbook.styles[a]=b),"https://"!==jade_settings.workbook.styles[a].substr(0,8)?f.jumpTo(0):f.yield(fetch(jade_settings.workbook.styles[a]),3);if(4!=f.nextAddress)return d=f.yieldResult,f.yield(d.text(),4);e=f.yieldResult;jade_settings.workbook.styles[a]=e;c&&(document.getElementById("head_style").remove(),
document.head.insertAdjacentHTML("beforeend",'<style id="head_style" data-name="'+a+'">'+jade_settings.workbook.styles[a]+jade_css_suffix+"</style>"));f.jumpToEnd()})};
Jade.set_style=function(a){var b=jade_css_suffix;a||(a="system",b="");"https://"===jade_settings.workbook.styles[a].substr(0,8)&&Jade.get_style(a);var c=document.getElementById("head_style");c.dataset.name!==a&&(c.remove(),document.head.insertAdjacentHTML("beforeend",'<style id="head_style" data-name="'+a+'">'+jade_settings.workbook.styles[a]+b+"</style>"))};Jade.panel_close_button=function(a){return'<div id="close_'+a+'" onclick="Jade.close_canvas(\''+a+'\')" class="top-corner" style="padding:5px 5px 0 5px;margin:5px 15px 0 0; cursor:pointer"><i class="far fa-window-close fa-2x"></i></i></div>'};
Jade.build_panel=function(a,b){var c=document.createElement("div");c.id=a;c.style.display="none";c.innerHTML=Jade.panel_close_button(a);jade_panels.includes(a)||jade_panels.push(a);document.body.appendChild(c);void 0===b&&(b=!0);b||Jade.hide_element("close_"+a)};
Jade.show_automations=function(a){for(var b=['<h2 style="margin:0 0 0 1rem">Active Automations</h2><ol>'],c=$jscomp.makeIterator(jade_code_panels),d=c.next();!d.done;d=c.next())if(d=ace.edit(d.value+"-content").getValue(),d=Jade.parse_code(d),!d.error){d=$jscomp.makeIterator(d.body);for(var e=d.next();!e.done;e=d.next()){var f=e.value;e=null;if("FunctionDeclaration"===f.type&&f.id&&f.id.name&&(0===f.params.length?e=f.id.name+"()":1===f.params.length&&f.async&&"excel ctx context".includes(f.params[0].name)&&
(e="Excel.run("+f.id.name+")"),e&&(f=window[f.id.name]+"",f.includes("Jade.listing:")))){f=f.split("Jade.listing:")[1].split("*/")[0];try{var g=JSON.parse(f);b.push('<li onclick="'+e+'" style="cursor:pointer"><b>'+g.name+"</b>: "+g.description+"</li>")}catch(h){console.log("Jade.listing was not valid JSON",f)}}}}1===b.length?b.push("There are currently no active automations in this workbook."):b.push("</ul>");Jade.open_canvas("panel_listings",b.join(""),a)};
Jade.show_panel=function(a){if(jade_code_panels.includes(a)){0===tag(a+"_function-names").length&&Jade.hide_element(a+"_function-names");tag(a+"_editor-page").style.height=Jade.editor_height();try{ace.edit(a+"-content").focus()}catch(d){console.log("could not access ace.  This is expected",d)}}(jade_panels.slice(0,3).includes(a)||jade_code_panels.includes(a))&&Jade.set_style();for(var b=$jscomp.makeIterator(jade_panels),c=b.next();!c.done;c=b.next())c=c.value,c===a?(tag("selector_"+a)&&(tag("selector_"+
a).value=a),tag(c).style.display="block",jade_panel_stack.push(c)):tag(c).style.display="none";if(jade_code_panels.includes(a))try{ace.edit(a+"-content").focus()}catch(d){console.log("could not access ace.  This is expected",d)}};Jade.toggle_wrap=function(a){a=ace.edit(a+"-content");"off"===a.getOptions().wrap?(a.setOptions({wrap:!0}),globalThis=!0):a.setOptions({wrap:"off"})};
Jade.add_code_editor=function(a,b,c,d,e){var f=jade_settings.user.ace_options;d||(d={cursorPosition:{row:0,column:0}});var g="panel_"+a.toLowerCase().split(" ").join("_")+"_module";jade_code_panels.push(g);jade_panel_labels.push(Jade.panel_name_to_panel_label(g));jade_panels.push(g);Jade.build_panel(g,!1);tag(g).dataset.module_name=a;tag(g).dataset.module_xmlid=c;tag(g).appendChild(Jade.get_panel_selector(g));a=document.createElement("div");a.className=g+"-content";c=document.createElement("div");
c.style.padding=".2rem";c.style.verticalAlign="middle";c.innerHTML='<button title="Save code to workbook" onclick="Jade.update_editor_script(\''+g+'\')">Save</button> <button  title="Save code to workbook and execute" onclick="Jade.code_runner(tag(\''+g+"_function-names').value,'"+g+'\')">Run</button> <select id="'+g+'_function-names"></select>';c.style.height="22px";c.style.fontFamily="auto";c.style.fontSize="1rem";c.style.padding=".2rem";c.style.backgroundColor="#eee";c.id=g+"_editor-bar";a.appendChild(c);
e=document.createElement("div");e.id=g+"_editor-page";e.style.width="100%";e.style.height=Jade.editor_height();e.style.display="inline-block";e.style.position="relative";c=document.createElement("div");c.id=g+"-content";c.dataset.edited=!1;c.innerHTML=b.toHtmlEntities();e.appendChild(c);a.appendChild(e);(new Promise(function(h,k){var l=document.createElement("script");document.body.appendChild(l);l.onload=h;l.onerror=k;l.async=!0;l.src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.13/ace.js"})).then(function(){var h=
ace.edit(g+"-content");h.on("blur",function(){window.event.target.parentElement.dataset.edited=!0});h.setOptions(f);h.session.setMode("ace/mode/javascript");h.moveCursorTo(d.cursorPosition.row,d.cursorPosition.column);h.commands.addCommand({name:"wrap",bindKey:{win:"Alt-z",mac:"Alt-z"},exec:function(k){k=$jscomp.makeIterator(jade_code_panels);for(var l=k.next();!l.done;l=k.next())if(l=l.value,"block"===tag(l).style.display){Jade.toggle_wrap(l);break}}});h.commands.addCommand({name:"run",bindKey:{win:"Ctrl-enter",
mac:"Command-enter"},exec:function(k){k=$jscomp.makeIterator(jade_code_panels);for(var l=k.next();!l.done;l=k.next())if(l=l.value,"block"===tag(l).style.display){Jade.code_runner(tag(l+"_function-names").value,l);break}}});h.commands.addCommand({name:"run_shift",bindKey:{win:"alt-enter",mac:"alt-enter"},exec:function(k){k=$jscomp.makeIterator(jade_code_panels);for(var l=k.next();!l.done;l=k.next())if(l=l.value,"block"===tag(l).style.display){Jade.code_runner(tag(l+"_function-names").value,l);break}}})});
a.style.display="block";Jade.parse_code(b).error||Jade.incorporate_code(b);tag(g).appendChild(a);Jade.load_function_names_select(b,g);d.func&&(tag(g+"_function-names").value=d.func);try{auto_exec()}catch(h){console.log("catch",h)}};Jade.code_runner=function(a,b){if("true"!==tag(b+"-content").dataset.edited||Jade.update_editor_script(b))a.includes("(excel)")?setTimeout("Excel.run("+a.split("(")[0]+")",0):setTimeout(a,0)};
Jade.init_output=function(){Jade.build_panel("panel_output",!1);tag("panel_output").appendChild(Jade.get_panel_selector("panel_output"));Jade.print('This panel shows the results of your calls to the "print" function.  Use "Jade.print(data)" to append text to the most recently printed block.',"About the Output Panel");Jade.print('\nUse "Jade.print(data, heading)" to start a new block.')};Jade.rebuild_examples=function(a){tag("panel_examples").innerHTML="";Jade.fill_examples(a)};
Jade.init_examples=function(){Jade.build_panel("panel_examples",!1);Jade.fill_examples()};
Jade.fill_examples=function(a){a||(a=jade_settings.workbook.examples_gist_id);var b=tag("panel_examples");b.appendChild(Jade.get_panel_selector("panel_examples"));var c=document.createElement("div");c.className="content";c.id="e_content";b.appendChild(c);b=[];c=$jscomp.makeIterator(a.split(","));for(a=c.next();!a.done;a=c.next())b.push(a.value.trim());c=[];var d=$jscomp.makeIterator(b);for(a=d.next();!a.done;a=d.next())c.push('<div id="'+a.value+'"></div>');tag("e_content").innerHTML=c.join("");for(a=
0;a<b.length;a++)Jade.get_example_html(b[a],a+1)};
Jade.get_example_html=function(a,b){var c="https://api.github.com/gists/"+a+"?"+Date.now(),d="https://gist.github.com/"+a;fetch(c).then(function(e){return e.text()}).then(function(e){e=JSON.parse(e);for(var f={},g=$jscomp.makeIterator(Object.keys(e.files)),h=g.next();!h.done;h=g.next())h=h.value,f[parseFloat(h.split("_").shift())]=h;var k=e.description.split(":");g=['<h2 style="cursor:pointer" title="Copy link to Example" onclick="Jade.copy_to_clipboard(\''+d+"')\">"+k.shift()+"</h2>"];g.push(k.join(":").trim());
h=0;var l=$jscomp.makeIterator(Object.keys(f));for(k=l.next();!k.done;k=l.next()){var m=k.value;h++;k=f[m].split(".");k.pop();k=k.join(".").split("_");k.shift();g.push('<p><a class="link" title="Show Code" onclick="Jade.show_example(\''+(100*b+h)+"','"+e.files[f[m]].raw_url+"',"+e.files[f[m]].content.split(/\r\n|\r|\n/).length+')"><b>'+h+". "+k.join(" ")+":</b> </a>");k=e.files[f[m]].content;k.includes("*/")&&g.push(k.split("*/")[0].split("/*")[1]);g.push('</p><div id="page'+(100*b+h)+'"></div>')}tag(a).innerHTML=
g.join("")})};
Jade.show_example=function(a,b,c){var d=tag("page"+a);""===d.innerHTML?(d.innerHTML='<img id="loading-image" width="50" src="assets/loading.gif" />',fetch(b).then(function(e){return e.text()}).then(function(e){tag("loading-image").remove();var f=document.createElement("div");f.id="example"+a+"_html";f.style.marginBottom="1rem";d.appendChild(f);f=22*c+17;f>window.innerHeight&&(f=window.innerHeight-60);var g=document.createElement("div");g.id="page_"+a;g.style.width="100%";g.style.height=f+"px";g.style.display=
"inline-block";g.style.position="relative";f=document.createElement("div");f.id="editor"+a;f.innerHTML=e.toHtmlEntities();g.appendChild(f);d.appendChild(g);(new Promise(function(h,k){var l=document.createElement("script");document.body.appendChild(l);l.onload=h;l.onerror=k;l.async=!0;l.src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.13/ace.js"})).then(function(){var h=ace.edit("editor"+a);h.on("blur",function(){Jade.update_script(a)});h.setTheme("ace/theme/tomorrow");h.setOptions({fontSize:"14pt"});
h.getSession().setUseWorker(!1);h.session.setMode("ace/mode/javascript");h.commands.addCommand({name:"wrap",bindKey:{win:"Alt-z",mac:"Alt-z"},exec:function(k){"off"===k.getOptions().wrap?(k.setOptions({wrap:!0}),globalThis=!0):k.setOptions({wrap:"off"})}})});d.style.display="block";Jade.incorporate_code(Jade.show_example_html_script(a));Jade.incorporate_code(e);setup();Jade.is_visible(tag("page_"+a))||tag("page_"+a).scrollIntoView(!1)})["catch"](function(e){console.log(e)})):"block"===d.style.display?
d.style.display="none":(d.style.display="block",Jade.incorporate_code(Jade.show_example_html_script(a)),Jade.incorporate_code(ace.edit("editor"+a).getValue()),setup(),Jade.is_visible(tag("page_"+a))||tag("page_"+a).scrollIntoView(!1))};Jade.show_example_html_script=function(a){return'function show_html(html){tag("example'+a+'_html").innerHTML=html}\n'};Jade.copy_to_clipboard=function(a){navigator.clipboard.writeText(a)};
Jade.update_script=function(a){var b=ace.edit("editor"+a),c=b.getValue(),d=Jade.parse_code(c);if(d.error)return alert(d.error,"Syntax Error"),b.moveCursorTo(d.error.split("(")[1].split(":")[0]-1,d.error.split("(")[1].split(":")[1].split(")")[0]),b.focus(),!1;Jade.incorporate_code(Jade.show_example_html_script(a));Jade.incorporate_code(c);return!0};Jade.parse_code=function(a){try{return acorn.parse(a,{ecmaVersion:8})}catch(b){return{error:b.message}}};
Jade.update_editor_script=function(a){var b=ace.edit(a+"-content"),c=b.getValue();Jade.write_module_to_workbook(c,a);tag(a+"_editor-page").style.height=Jade.editor_height();Jade.incorporate_code('function show_html(html){open_canvas("html", html)}');var d=Jade.parse_code(c);if(d.error)return alert(d.error,"Syntax Error"),b.moveCursorTo(d.error.split("(")[1].split(":")[0]-1,d.error.split("(")[1].split(":")[1].split(")")[0]),b.focus(),!1;Jade.incorporate_code(c);Jade.load_function_names_select(d,a);
return!0};Jade.incorporate_code=function(a){var b=document.createElement("script");b.innerHTML=a;document.body.appendChild(b);document.body.lastChild.remove()};
Jade.write_module_to_workbook=function(a,b){var c={fontSize:"14pt"};tag(b+"_function-names");try{var d=ace.edit(b+"-content");jade_settings.cursorPosition=d.getCursorPosition();c=d.getOptions()}catch(f){}d=tag(b).dataset.module_name;var e=tag(b).dataset.module_xmlid;e?Jade.save_module_to_workbook(a,d,jade_settings,e,c):Jade.save_module_to_workbook(a,d,jade_settings,e,c,tag(b))};
Jade.save_module_to_workbook=function(a,b,c,d,e,f){Excel.run(function(g){var h,k,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){if(1==m.nextAddress){c||(c={cursorPosition:{row:0,column:0}});h="<module xmlns='http://schemas.gove.net/code/1.0'><name>"+b+"</name><jade_settings>"+btoa(JSON.stringify(c))+"</jade_settings><options>"+btoa(null)+"</options><code>"+btoa(a)+"</code></module>";if(d)return k=g.workbook.customXmlParts.getItem(d),k.setXml(h),g.sync(),m.jumpTo(0);l=g.workbook.customXmlParts.add(h);
l.load("id");return m.yield(g.sync(),3)}jade_settings.workbook.code_module_ids.push(l.id);Jade.write_settings_to_workbook();f&&(f.dataset.module_xmlid=l.id);m.jumpToEnd()})})};
Jade.load_function_names_select=function(a,b){var c="string"===typeof a?Jade.parse_code(a):a;if(!c.error){for(var d=tag(b+"_function-names"),e=d.value;0<d.options.length;)d.remove(0);c=$jscomp.makeIterator(c.body);for(var f=c.next();!f.done;f=c.next()){f=f.value;var g=null;if("FunctionDeclaration"===f.type&&f.id&&f.id.name&&(0===f.params.length?g=f.id.name+"()":1===f.params.length&&f.async&&"excel ctx context".includes(f.params[0].name)&&(g=f.id.name+"(excel)"),g)){var h=document.createElement("option");
g===e&&(h.selected="selected");h.text=f.id.name;h.value=g;d.add(h)}}0===d.length?Jade.hide_element(d):Jade.show_element(d)}};
Jade.get_panel_selector=function(a){var b=Jade.panel_name_to_panel_label(a),c=document.createElement("select");jade_panel_labels.includes(b)||jade_panel_labels.push(b);c.className="panel-selector";Jade.update_panel_selector(c);b=$jscomp.makeIterator(document.getElementsByClassName("panel-selector"));for(var d=b.next();!d.done;d=b.next())Jade.update_panel_selector(d.value);c.value=a;c.style.height="40px";c.id="selector_"+a;c.onchange=Jade.select_page;return c};
Jade.update_panel_selector=function(a){for(;0<a.length;)a.remove(0);for(var b=0;b<jade_panel_labels.length;b++){var c=document.createElement("option");c.value=Jade.panel_label_to_panel_name(jade_panel_labels[b]);c.text=jade_panel_labels[b];c.className="panel-selector-option";a.appendChild(c)}};Jade.panel_label_to_panel_name=function(a){return"panel_"+a.toLocaleLowerCase().split(" ").join("_")};Jade.panel_name_to_panel_label=function(a){a=a.replace("panel_","");a=a.split("_").join(" ");return a.toTitleCase()};
Jade.select_page=function(){Jade.show_panel(window.event.target.value)};Jade.show_element=function(a){a="string"===typeof a?tag(a):a;a.className=a.className.replaceAll("hidden","")};Jade.hide_element=function(a){if(a="string"===typeof a?tag(a):a)a.className?a.className.includes("hidden")||(a.className=(a.className+" hidden").trim()):a.className="hidden"};Jade.toggle_element=function(a){a="string"===typeof a?tag(a):a;a.className.includes("hidden")?Jade.show_element(a):Jade.hide_element(a)};
Jade.editor_height=function(){return window.innerHeight-73+"px"};
Jade.default_code=function(a){var b='async function write_timestamp(excel){\n      /*Jade.listing:{"name":"Timestamp","description":"This sample function records the current time in the selected cells"}*/\n    excel.workbook.getSelectedRange().values = new Date();\n    await excel.sync();\n  }\n\n  function auto_exec(){\n    // This function is called when the addin opens.\n    // un-comment a line below to take action on open.\n\n    // Jade.open_automations() // displays a list of functions for a user\n  ';return a?
b+("  // Jade.show_panel('"+a+"')      // shows this code editor\n  }"):b+"  // Jade.open_editor()      // shows the code editor\n  }"};Jade.show_import_module=function(){jade_settings.workbook.module_to_import&&(tag("gist-url").value=jade_settings.workbook.module_to_import);Jade.toggle_element("import-module");tag("gist-url").focus()};
Jade.is_visible=function(a){a=a.getBoundingClientRect();return 0<=a.top&&0<=a.left&&a.bottom<=(window.innerHeight||document.documentElement.clientHeight)&&a.right<=(window.innerWidth||document.documentElement.clientWidth)};String.prototype.toHtmlEntities=function(){return this.replace(/./gm,function(a){return a.match(/[a-z0-9\s]+/i)?a:"&#"+a.charCodeAt(0)+";"})};
String.prototype.toTitleCase=function(){str=this.toLowerCase().split(" ");for(var a=0;a<str.length;a++)str[a]=str[a].charAt(0).toUpperCase()+str[a].slice(1);return str.join(" ")};function tag(a){return document.getElementById(a)}
function alert(a,b){tag("jade-alert")&&tag("jade-alert").remove();b||(b="System Message");var c=document.createElement("div");c.className="jade-alert";c.id="jade-alert";var d=document.createElement("div");d.className="jade-alert-header";d.innerHTML=b+'<div class="jade-alert-close"><i class="fas fa-times" style="color:white;margin-right:.3rem;cursor:pointer" onclick="this.parentNode.parentNode.parentNode.remove()"></div>';var e=document.createElement("div");e.className="jade-alert-body";e.innerHTML=
a;c.appendChild(d);c.appendChild(e);document.body.appendChild(c)};