const jade_settings={};let jade_css_suffix="";const jade_panels=["panel_home","panel_examples"],jade_panel_labels=["Home","Examples","Output"],jade_code_panels=[],jade_panel_stack=["panel_home"];
class Jade{static async load_gist(a){try{const b=await (await fetch(`https://api.github.com/gists/${a}?${new Date}`)).json();for(const c of Object.values(b.files))Jade.incorporate_code(c.content);auto_exec();Jade.incorporate_code("auto_exec=null")}catch(b){}}static async import_code_module(a){jade_settings.workbook.module_to_import=a;Jade.hide_element("import-module");Jade.save_settings();if(a){if("http"===a.substr(0,4))if(a.toLowerCase().includes("gist.github.com")){a.split("/");var b="https://api.github.com/gists/"+
c[c.length-1]+"?"+new Date}else b=a;else b="https://api.github.com/gists/"+a+"?"+new Date;try{var c=await (await fetch(b)).text()}catch(e){alert(e.message,"Error Loading Module");console.log("Error fetching gist",e);return}a=[];try{var d=JSON.parse(c);try{for(const e of Object.values(d.files))a.push({name:e.filename.split(".js")[0],code:e.content})}catch(e){alert(e.message,"Error Parsing Gist");return}}catch(e){d=null;if(c.includes("ace.module:"))try{d=JSON.parse(c.split("ace.module:")[1].split("*/")[0]).name}catch(g){b=
b.split("/"),d=b[b.length-1]}if(!d){for(b=1;tag(Jade.panel_label_to_panel_name("Code "+b));)b++;a.push({name:"Code "+b,code:c})}}for(const e of a)tag(Jade.panel_label_to_panel_name(e.name+" Module"))?ace.edit(Jade.panel_label_to_panel_name(e.name)+"_module-content").setValue(e.code):Jade.add_code_module(e.name,e.code)}}static set_css(a){jade_css_suffix=a}static add_library(a){const b=document.createElement("script");b.setAttribute("src",a);document.head.appendChild(b)}static close_canvas(){jade_panel_stack.pop();
Jade.show_panel(jade_panel_stack.pop())}static open_editor(){Jade.show_panel(jade_code_panels[0])}static open_output(){Jade.show_panel("panel_output")}static open_automations(a){Jade.show_automations(a)}static reset(){Jade.show_panel("panel_home")}static open_canvas(a,b,c,d){d&&Jade.set_style(d);tag(a)||Jade.build_panel(a);jade_panels.includes(a)||jade_panels.push(a);Jade.show_panel(a);b&&(c||void 0===c?tag(a).innerHTML=Jade.panel_close_button(a)+b:tag(a).innerHTML=b)}static print(a,b){tag("panel_output").lastChild.lastChild.firstChild.tagName||
b||(b="");if(b){const c=document.createElement("div");c.className="jade-output";const d=document.createElement("div");d.className="jade-output-header";const e=new Date;let g=" am",f=e.getHours();11<f&&(g="pm",12<f&&(f-=12));d.innerHTML='<span class="jade-output-time">'+f+":"+("0"+e.getMinutes()).slice(-2)+":"+("0"+e.getSeconds()).slice(-2)+g+"</span> "+b+'<div class="jade-output-close"><i class="fas fa-times" style="color:white;margin-right:.3rem;cursor:pointer" onclick="this.parentNode.parentNode.parentNode.remove()"></div>';
b=document.createElement("div");b.className="jade-output-body";b.innerHTML='<div style="margin:0;font-family: monospace;">'+a.replaceAll("\n","<br />")+"<br /></div>";c.appendChild(d);c.appendChild(b);tag("panel_output").appendChild(c)}else tag("panel_output").lastChild.lastChild.firstChild.innerHTML+=a.replaceAll("\n","<br />")+"<br />"}static open_examples(){Jade.set_style();Jade.show_panel("panel_examples")}static set_theme(a){Jade.set_style(a)}static list_themes(){for(const []of Object.entries(jade_settings.workbook.styles));
}static officeReady(a){a.host===Office.HostType.Excel?Excel.run(async b=>{const c=b.workbook.settings.getItemOrNullObject("jade").load("value");await b.sync();c.isNullObject?(jade_settings.user={ace_options:{selectionStyle:"line",highlightActiveLine:!0,highlightSelectedWord:!0,readOnly:!1,copyWithEmptySelection:!1,cursorStyle:"ace",mergeUndoDeltas:!0,behavioursEnabled:!0,wrapBehavioursEnabled:!0,enableAutoIndent:!0,showLineNumbers:!0,hScrollBarAlwaysVisible:!1,vScrollBarAlwaysVisible:!1,highlightGutterLine:!0,
animatedScroll:!1,showInvisibles:!1,showPrintMargin:!1,printMarginColumn:80,printMargin:80,fadeFoldWidgets:!1,showFoldWidgets:!0,displayIndentGuides:!0,showGutter:!0,fontSize:"14pt",scrollPastEnd:0,theme:"ace/theme/tomorrow",maxPixelHeight:0,useTextareaForIME:!0,scrollSpeed:2,dragDelay:0,dragEnabled:!0,focusTimeout:0,tooltipFollowsMouse:!0,firstLineNumber:1,overwrite:!1,newLineMode:"auto",useWorker:!1,navigateWithinSoftTabs:!1,wrap:!0,indentedSoftWrap:!0,foldStyle:"markbegin",mode:"ace/mode/javascript",
enableMultiselect:!0,enableBlockSelect:!0,tabSize:2,useSoftTabs:!0}},jade_settings.workbook={code_module_ids:[],examples_gist_id:"904983747625c3fdc8dfa69e0aaa0f08",styles:{system:null,none:"/*No Theme CSS Used*/",mvp:"https://cdnjs.cloudflare.com/ajax/libs/mvp.css/1.8.0/mvp.css",marx:"https://cdnjs.cloudflare.com/ajax/libs/marx/4.0.0/marx.min.css",water:"https://cdn.jsdelivr.net/npm/water.css@2/out/water.css","dark water":"https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css",sajura:"https://unpkg.com/sakura.css/css/sakura.css",
tacit:"https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css-1.5.5.min.css",pure:"https://unpkg.com/purecss@2.0.6/build/pure-min.css",picnic:"https://cdn.jsdelivr.net/npm/picnic",wing:"https://unpkg.com/wingcss",chota:"https://unpkg.com/chota@latest",bootstrap:"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"}}):(jade_settings.workbook=c.value.workbook,jade_settings.user=c.value.user);Jade.configure_settings();Jade.start_me_up()}):(document.getElementById("sideload-msg").style.display=
"flex",document.getElementById("menu").style.display="none")}static start_me_up(){jade_settings.workbook.styles.system=tag("head_style").innerText;jade_panels.push("panel_home");jade_settings.workbook.load_gist_id&&Jade.load_gist(jade_settings.workbook.load_gist_id);tag("new-module-name").addEventListener("keyup",function(a){a.preventDefault();"Enter"===a.key&&tag("module-add-button").click()});tag("gist-url").addEventListener("keyup",function(a){a.preventDefault();"Enter"===a.key&&tag("module-import-button").click()});
window.addEventListener("resize",function(a){for(const b of jade_code_panels)tag(b+"_editor-page").style.height=Jade.editor_height()},!0);Jade.init_examples();Jade.init_output();0<jade_settings.workbook.code_module_ids.length&&Jade.show_element("open-editor");Excel.run(async a=>{const b=new DOMParser;for(const e of jade_settings.workbook.code_module_ids){var c=a.workbook.customXmlParts.getItem(e).getXml();await a.sync();var d=b.parseFromString(c.value,"application/xml");c=d.getElementsByTagName("name")[0].textContent;
const g=atob(d.getElementsByTagName("code")[0].textContent);d=atob(d.getElementsByTagName("options")[0].textContent);Jade.add_code_editor(c,g,e,null,JSON.parse(d))}})}static configure_settings(){tag("jade-font-size").value=jade_settings.user.ace_options.fontSize.replace("pt","");!1===jade_settings.user.ace_options.wrap?tag("jade-word-wrap").value="no-wrap":jade_settings.user.ace_options.indentedSoftWrap?tag("jade-word-wrap").value="wrap-indented":tag("jade-word-wrap").value="wrap";tag("examples-gist-id").value=
jade_settings.workbook.examples_gist_id;tag("jade-theme").value=jade_settings.user.ace_options.theme.split("/")[2];tag("jade-line-numbers").checked=jade_settings.user.ace_options.showGutter;jade_settings.workbook.load_gist_id&&(tag("load-gist-id").value=jade_settings.workbook.load_gist_id)}static async save_settings(){tag("examples-gist-id").value&&jade_settings.workbook.examples_gist_id!==tag("examples-gist-id").value&&Jade.rebuild_examples(tag("examples-gist-id").value);jade_settings.workbook.examples_gist_id=
tag("examples-gist-id").value;jade_settings.workbook.load_gist_id=tag("load-gist-id").value;jade_settings.user.ace_options.theme="ace/theme/"+tag("jade-theme").value;jade_settings.user.ace_options.fontSize=tag("jade-font-size").value+"pt";jade_settings.user.ace_options.showGutter=tag("jade-line-numbers").checked;switch(tag("jade-word-wrap").value){case "wrap":jade_settings.user.ace_options.wrap=!0;jade_settings.user.ace_options.indentedSoftWrap=!1;break;case "wrap-indented":jade_settings.user.ace_options.wrap=
!0;jade_settings.user.ace_options.indentedSoftWrap=!0;break;default:jade_settings.user.ace_options.wrap="off"}Jade.apply_editor_options(jade_settings.user.ace_options);await Jade.write_settings_to_workbook();Jade.hide_element("settings-page")}static async write_settings_to_workbook(){await Excel.run(async a=>{a.workbook.settings.add("jade",jade_settings);await a.sync()})}static apply_editor_options(a){for(const b of jade_code_panels)ace.edit(b+"-content").setOptions(a)}static async submit_feedback(){const a=
[];""===tag("fb-type").value&&a.push("<li>You must indicate the <b>type</b> of your feedback.</li>");""===tag("fb-text").value&&a.push("<li>You must provide the <b>text</b> of your feedback.</li>");""===tag("fb-platform").value&&a.push("<li>You must provide the <b>platform</b> you are using.</li>");if(0===a.length){var b=[];b.push("entry.1033992853=");b.push(encodeURIComponent(tag("fb-type").value));b.push("&entry.482647522=");b.push(encodeURIComponent(tag("fb-platform").value));b.push("&entry.1230850697=");
b.push(encodeURIComponent(tag("fb-email").value));b.push("&entry.1009690762=");b.push(encodeURIComponent(tag("fb-text").value));b.push("&entry.64124153=");b.push(encodeURIComponent("Addin"));tag("fb-message").innerHTML="";b={method:"POST",mode:"no-cors",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b.join("")};try{await (await fetch("https://docs.google.com/forms/u/0/d/e/1FAIpQLSeRCZKHMU0HvXEiia8dn6hL0DfGoAH-PCJZolfiN1S_O90eSQ/formResponse",b)).text();tag("fb-message").style.color=
"green";switch(tag("fb-type").value){case "Feature Resuest":a.push("Thanks for your feedback. Were not sure when we'll be updaing next but thanks for helping us understand your needs.");break;case "Report Issue":a.push("Thanks for reporing this issue. While we cannot respond to every problem report, we'll do what we can.");break;case "Offer to help with development":a.push("Thanks for offering to help on this project.  We'll take a look at your comment and get back to you--if you provided a valid email address.");
break;case "Praise for Addin":a.push("Thanks a million. We thrive on positive feedback!");break;default:a.push("Thanks for asking this question. While we cannot respond to every question, we'll do what we can.")}tag("fb-message").innerHTML=a.join("");tag("fb-message").scrollIntoView(!0);setTimeout(function(){Jade.hide_element("survey");tag("fb-message").innerHTML=""},1E4)}catch(c){tag("fb-message").style.color="red",tag("fb-message").innerHTML='Oops.  It looks as though there was a network error.  Your can tray again later or submit at our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeRCZKHMU0HvXEiia8dn6hL0DfGoAH-PCJZolfiN1S_O90eSQ/viewform?usp=pp_url&entry.64124153=web" target="_blank">Google Form<a>.',
window.scrollTo(0,document.body.scrollHeight),tag("fb-message").scrollIntoView(!0)}}else tag("fb-message").style.color="red",tag("fb-message").innerHTML="<ul>"+a.join("")+"</ul>",tag("fb-message").scrollIntoView(!0)}static add_code_module(a,b){a||="code";for(const c of jade_code_panels)if(c===Jade.panel_label_to_panel_name(a)+"_module"){alert('A module named "'+a+'" already exists in this workbook.  <br><br>Choose a differnt name.',"Invalid Module Name");return}b||=0===jade_code_panels.length?Jade.default_code():
Jade.default_code("panel_"+a.toLowerCase().split(" ").join("_")+"_module");Jade.add_code_editor(a,b,"");Jade.hide_element("add-module");Jade.show_element("open-editor");Jade.show_panel(jade_code_panels[jade_code_panels.length-1]);Jade.write_module_to_workbook(b,jade_code_panels[jade_code_panels.length-1])}static async get_style(a,b,c){void 0===c&&(c=!0);jade_settings.workbook.styles[a]||(jade_settings.workbook.styles[a]=b);"https://"===jade_settings.workbook.styles[a].substr(0,8)&&(b=await (await fetch(jade_settings.workbook.styles[a])).text(),
jade_settings.workbook.styles[a]=b,c&&(document.getElementById("head_style").remove(),document.head.insertAdjacentHTML("beforeend",'<style id="head_style" data-name="'+a+'">'+jade_settings.workbook.styles[a]+jade_css_suffix+"</style>")))}static set_style(a){let b=jade_css_suffix;a||(a="system",b="");"https://"===jade_settings.workbook.styles[a].substr(0,8)&&Jade.get_style(a);const c=document.getElementById("head_style");c.dataset.name!==a&&(c.remove(),document.head.insertAdjacentHTML("beforeend",
'<style id="head_style" data-name="'+a+'">'+jade_settings.workbook.styles[a]+b+"</style>"))}static panel_close_button(a){return'<div id="close_'+a+'" onclick="Jade.close_canvas(\''+a+'\')" class="top-corner" style="padding:5px 5px 0 5px;margin:5px 15px 0 0; cursor:pointer"><i class="far fa-window-close fa-2x"></i></i></div>'}static build_panel(a,b){const c=document.createElement("div");c.id=a;c.style.display="none";c.innerHTML=Jade.panel_close_button(a);jade_panels.includes(a)||jade_panels.push(a);
document.body.appendChild(c);void 0===b&&(b=!0);b||Jade.hide_element("close_"+a)}static show_automations(a){const b=['<h2 style="margin:0 0 0 1rem">Active Automations</h2><ol>'];for(const e of jade_code_panels){var c=ace.edit(e+"-content").getValue();c=Jade.parse_code(c);if(!c.error)for(const g of c.body)if(c=null,"FunctionDeclaration"===g.type&&g.id&&g.id.name&&(0===g.params.length?c=g.id.name+"()":1===g.params.length&&g.async&&"excel ctx context".includes(g.params[0].name)&&(c="Excel.run("+g.id.name+
")"),c)){var d=window[g.id.name]+"";if(d.includes("Jade.listing:")){d=d.split("Jade.listing:")[1].split("*/")[0];try{const f=JSON.parse(d);b.push('<li onclick="'+c+'" style="cursor:pointer"><b>'+f.name+"</b>: "+f.description+"</li>")}catch(f){console.log("Jade.listing was not valid JSON",d)}}}}1===b.length?b.push("There are currently no active automations in this workbook."):b.push("</ul>");Jade.open_canvas("panel_listings",b.join(""),a)}static show_panel(a){if(jade_code_panels.includes(a)){0===tag(a+
"_function-names").length&&Jade.hide_element(a+"_function-names");tag(a+"_editor-page").style.height=Jade.editor_height();try{ace.edit(a+"-content").focus()}catch(b){console.log("could not access ace.  This is expected",b)}}(jade_panels.slice(0,3).includes(a)||jade_code_panels.includes(a))&&Jade.set_style();for(const b of jade_panels)b===a?(tag("selector_"+a)&&(tag("selector_"+a).value=a),tag(b).style.display="block",jade_panel_stack.push(b)):tag(b).style.display="none";if(jade_code_panels.includes(a))try{ace.edit(a+
"-content").focus()}catch(b){console.log("could not access ace.  This is expected",b)}}static toggle_wrap(a){a=ace.edit(a+"-content");"off"===a.getOptions().wrap?(a.setOptions({wrap:!0}),globalThis=!0):a.setOptions({wrap:"off"})}static add_code_editor(a,b,c,d,e){let g=jade_settings.user.ace_options;d||={cursorPosition:{row:0,column:0}};const f="panel_"+a.toLowerCase().split(" ").join("_")+"_module";jade_code_panels.push(f);jade_panel_labels.push(Jade.panel_name_to_panel_label(f));jade_panels.push(f);
Jade.build_panel(f,!1);tag(f).dataset.module_name=a;tag(f).dataset.module_xmlid=c;tag(f).appendChild(Jade.get_panel_selector(f));a=document.createElement("div");a.className=f+"-content";c=document.createElement("div");c.style.padding=".2rem";c.style.verticalAlign="middle";c.innerHTML='<button title="Save code to workbook" onclick="Jade.update_editor_script(\''+f+'\')">Save</button> <button  title="Save code to workbook and execute" onclick="Jade.code_runner(tag(\''+f+"_function-names').value,'"+f+
'\')">Run</button> <select id="'+f+'_function-names"></select>';c.style.height="22px";c.style.fontFamily="auto";c.style.fontSize="1rem";c.style.padding=".2rem";c.style.backgroundColor="#eee";c.id=f+"_editor-bar";a.appendChild(c);e=document.createElement("div");e.id=f+"_editor-page";e.style.width="100%";e.style.height=Jade.editor_height();e.style.display="inline-block";e.style.position="relative";c=document.createElement("div");c.id=f+"-content";c.dataset.edited=!1;c.innerHTML=b.toHtmlEntities();e.appendChild(c);
a.appendChild(e);(new Promise((h,l)=>{const k=document.createElement("script");document.body.appendChild(k);k.onload=h;k.onerror=l;k.async=!0;k.src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.13/ace.js"})).then(()=>{const h=ace.edit(f+"-content");h.on("blur",function(){window.event.target.parentElement.dataset.edited=!0});h.setOptions(g);h.session.setMode("ace/mode/javascript");h.moveCursorTo(d.cursorPosition.row,d.cursorPosition.column);h.commands.addCommand({name:"wrap",bindKey:{win:"Alt-z",
mac:"Alt-z"},exec:function(l){for(const k of jade_code_panels)if("block"===tag(k).style.display){Jade.toggle_wrap(k);break}}});h.commands.addCommand({name:"run",bindKey:{win:"Ctrl-enter",mac:"Command-enter"},exec:function(l){for(const k of jade_code_panels)if("block"===tag(k).style.display){Jade.code_runner(tag(k+"_function-names").value,k);break}}});h.commands.addCommand({name:"run_shift",bindKey:{win:"alt-enter",mac:"alt-enter"},exec:function(l){for(const k of jade_code_panels)if("block"===tag(k).style.display){Jade.code_runner(tag(k+
"_function-names").value,k);break}}})});a.style.display="block";Jade.parse_code(b).error||Jade.incorporate_code(b);tag(f).appendChild(a);Jade.load_function_names_select(b,f);d.func&&(tag(f+"_function-names").value=d.func);try{auto_exec()}catch(h){console.log("catch",h)}}static code_runner(a,b){if("true"!==tag(b+"-content").dataset.edited||Jade.update_editor_script(b))a.includes("(excel)")?setTimeout("Excel.run("+a.split("(")[0]+")",0):setTimeout(a,0)}static init_output(){Jade.build_panel("panel_output",
!1);tag("panel_output").appendChild(Jade.get_panel_selector("panel_output"));Jade.print('This panel shows the results of your calls to the "print" function.  Use "Jade.print(data)" to append text to the most recently printed block.',"About the Output Panel");Jade.print('\nUse "Jade.print(data, heading)" to start a new block.')}static rebuild_examples(a){tag("panel_examples").innerHTML="";Jade.fill_examples(a)}static init_examples(){Jade.build_panel("panel_examples",!1);Jade.fill_examples()}static fill_examples(a){a||
(a=jade_settings.workbook.examples_gist_id);var b=tag("panel_examples");b.appendChild(Jade.get_panel_selector("panel_examples"));const c=document.createElement("div");c.className="content";c.id="e_content";b.appendChild(c);b=[];for(const e of a.split(","))b.push(e.trim());a=[];for(var d of b)a.push(`<div id="${d}"></div>`);tag("e_content").innerHTML=a.join("");for(d=0;d<b.length;d++)Jade.get_example_html(b[d],d+1)}static get_example_html(a,b){const c=`https://api.github.com/gists/${a}?${Date.now()}`,
d=`https://gist.github.com/${a}`;fetch(c).then(e=>e.text()).then(e=>{e=JSON.parse(e);const g={};for(var f of Object.keys(e.files))g[parseFloat(f.split("_").shift())]=f;f=e.description.split(":");const h=[`<h2 style="cursor:pointer" title="Copy link to Example" onclick="Jade.copy_to_clipboard('${d}')">${f.shift()}</h2>`];h.push(f.join(":").trim());let l=0;for(const k of Object.keys(g))l++,f=g[k].split("."),f.pop(),f=f.join(".").split("_"),f.shift(),h.push(`<p><a class="link" title="Show Code" onclick="Jade.show_example('${100*
b+l}','${e.files[g[k]].raw_url}',${e.files[g[k]].content.split(/\r\n|\r|\n/).length})"><b>${l}. ${f.join(" ")}:</b> </a>`),f=e.files[g[k]].content,f.includes("*/")&&h.push(f.split("*/")[0].split("/*")[1]),h.push(`</p><div id="page${100*b+l}"></div>`);tag(a).innerHTML=h.join("")})}static show_example(a,b,c){const d=tag("page"+a);""===d.innerHTML?(d.innerHTML='<img id="loading-image" width="50" src="assets/loading.gif" />',fetch(b).then(e=>e.text()).then(e=>{tag("loading-image").remove();var g=document.createElement("div");
g.id="example"+a+"_html";g.style.marginBottom="1rem";d.appendChild(g);g=22*c+17;g>window.innerHeight&&(g=window.innerHeight-60);const f=document.createElement("div");f.id="page_"+a;f.style.width="100%";f.style.height=g+"px";f.style.display="inline-block";f.style.position="relative";g=document.createElement("div");g.id="editor"+a;g.innerHTML=e.toHtmlEntities();f.appendChild(g);d.appendChild(f);(new Promise((h,l)=>{const k=document.createElement("script");document.body.appendChild(k);k.onload=h;k.onerror=
l;k.async=!0;k.src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.13/ace.js"})).then(()=>{const h=ace.edit("editor"+a);h.on("blur",function(){Jade.update_script(a)});h.setTheme("ace/theme/tomorrow");h.setOptions({fontSize:"14pt"});h.getSession().setUseWorker(!1);h.session.setMode("ace/mode/javascript");h.commands.addCommand({name:"wrap",bindKey:{win:"Alt-z",mac:"Alt-z"},exec:function(l){"off"===l.getOptions().wrap?(l.setOptions({wrap:!0}),globalThis=!0):l.setOptions({wrap:"off"})}})});d.style.display=
"block";Jade.incorporate_code(Jade.show_example_html_script(a));Jade.incorporate_code(e);setup();Jade.is_visible(tag("page_"+a))||tag("page_"+a).scrollIntoView(!1)}).catch(e=>{console.log(e)})):"block"===d.style.display?d.style.display="none":(d.style.display="block",Jade.incorporate_code(Jade.show_example_html_script(a)),Jade.incorporate_code(ace.edit("editor"+a).getValue()),setup(),Jade.is_visible(tag("page_"+a))||tag("page_"+a).scrollIntoView(!1))}static show_example_html_script(a){return'function show_html(html){tag("example'+
a+'_html").innerHTML=html}\n'}static copy_to_clipboard(a){navigator.clipboard.writeText(a)}static update_script(a){const b=ace.edit("editor"+a),c=b.getValue(),d=Jade.parse_code(c);if(d.error)return alert(d.error,"Syntax Error"),b.moveCursorTo(d.error.split("(")[1].split(":")[0]-1,d.error.split("(")[1].split(":")[1].split(")")[0]),b.focus(),!1;Jade.incorporate_code(Jade.show_example_html_script(a));Jade.incorporate_code(c);return!0}static parse_code(a){try{return acorn.parse(a,{ecmaVersion:8})}catch(b){return{error:b.message}}}static update_editor_script(a){const b=
ace.edit(a+"-content"),c=b.getValue();Jade.write_module_to_workbook(c,a);tag(a+"_editor-page").style.height=Jade.editor_height();Jade.incorporate_code('function show_html(html){open_canvas("html", html)}');const d=Jade.parse_code(c);if(d.error)return alert(d.error,"Syntax Error"),b.moveCursorTo(d.error.split("(")[1].split(":")[0]-1,d.error.split("(")[1].split(":")[1].split(")")[0]),b.focus(),!1;Jade.incorporate_code(c);Jade.load_function_names_select(d,a);return!0}static incorporate_code(a){const b=
document.createElement("script");b.innerHTML=a;document.body.appendChild(b);document.body.lastChild.remove()}static write_module_to_workbook(a,b){let c={fontSize:"14pt"};tag(b+"_function-names");try{var d=ace.edit(b+"-content");jade_settings.cursorPosition=d.getCursorPosition();c=d.getOptions()}catch(g){}d=tag(b).dataset.module_name;let e=tag(b).dataset.module_xmlid;e?Jade.save_module_to_workbook(a,d,jade_settings,e,c):Jade.save_module_to_workbook(a,d,jade_settings,e,c,tag(b))}static save_module_to_workbook(a,
b,c,d,e,g){Excel.run(async f=>{c||={cursorPosition:{row:0,column:0}};var h="<module xmlns='http://schemas.gove.net/code/1.0'><name>"+b+"</name><jade_settings>"+btoa(JSON.stringify(c))+"</jade_settings><options>"+btoa(null)+"</options><code>"+btoa(a)+"</code></module>";d?(f.workbook.customXmlParts.getItem(d).setXml(h),f.sync()):(h=f.workbook.customXmlParts.add(h),h.load("id"),await f.sync(),jade_settings.workbook.code_module_ids.push(h.id),Jade.write_settings_to_workbook(),g&&(g.dataset.module_xmlid=
h.id))})}static load_function_names_select(a,b){var c="string"===typeof a?Jade.parse_code(a):a;if(!c.error){b=tag(b+"_function-names");for(a=b.value;0<b.options.length;)b.remove(0);for(const d of c.body)if(c=null,"FunctionDeclaration"===d.type&&d.id&&d.id.name&&(0===d.params.length?c=d.id.name+"()":1===d.params.length&&d.async&&"excel ctx context".includes(d.params[0].name)&&(c=d.id.name+"(excel)"),c)){const e=document.createElement("option");c===a&&(e.selected="selected");e.text=d.id.name;e.value=
c;b.add(e)}0===b.length?Jade.hide_element(b):Jade.show_element(b)}}static get_panel_selector(a){const b=Jade.panel_name_to_panel_label(a),c=document.createElement("select");jade_panel_labels.includes(b)||jade_panel_labels.push(b);c.className="panel-selector";Jade.update_panel_selector(c);for(const d of document.getElementsByClassName("panel-selector"))Jade.update_panel_selector(d);c.value=a;c.style.height="40px";c.id="selector_"+a;c.onchange=Jade.select_page;return c}static update_panel_selector(a){for(;0<
a.length;)a.remove(0);for(let c=0;c<jade_panel_labels.length;c++){var b=document.createElement("option");b.value=Jade.panel_label_to_panel_name(jade_panel_labels[c]);b.text=jade_panel_labels[c];b.className="panel-selector-option";a.appendChild(b)}}static panel_label_to_panel_name(a){return"panel_"+a.toLocaleLowerCase().split(" ").join("_")}static panel_name_to_panel_label(a){a=a.replace("panel_","");a=a.split("_").join(" ");return a.toTitleCase()}static select_page(){Jade.show_panel(window.event.target.value)}static show_element(a){a=
"string"===typeof a?tag(a):a;a.className=a.className.replaceAll("hidden","")}static hide_element(a){if(a="string"===typeof a?tag(a):a)a.className?a.className.includes("hidden")||(a.className=(a.className+" hidden").trim()):a.className="hidden"}static toggle_element(a){a="string"===typeof a?tag(a):a;a.className.includes("hidden")?Jade.show_element(a):Jade.hide_element(a)}static editor_height(){return window.innerHeight-73+"px"}static default_code(a){let b='async function write_timestamp(excel){\n      /*Jade.listing:{"name":"Timestamp","description":"This sample function records the current time in the selected cells"}*/\n    excel.workbook.getSelectedRange().values = new Date();\n    await excel.sync();\n  }\n  \n  function auto_exec(){\n    // This function is called when the addin opens.\n    // un-comment a line below to take action on open.\n  \n    // Jade.open_automations() // displays a list of functions for a user\n  ';
return a?b+`  // Jade.show_panel('${a}')      // shows this code editor
  }`:b+"  // Jade.open_editor()      // shows the code editor\n  }"}static show_import_module(){jade_settings.workbook.module_to_import&&(tag("gist-url").value=jade_settings.workbook.module_to_import);Jade.toggle_element("import-module");tag("gist-url").focus()}static is_visible(a){a=a.getBoundingClientRect();return 0<=a.top&&0<=a.left&&a.bottom<=(window.innerHeight||document.documentElement.clientHeight)&&a.right<=(window.innerWidth||document.documentElement.clientWidth)}}
String.prototype.toHtmlEntities=function(){return this.replace(/./gm,function(a){return a.match(/[a-z0-9\s]+/i)?a:"&#"+a.charCodeAt(0)+";"})};String.prototype.toTitleCase=function(){str=this.toLowerCase().split(" ");for(var a=0;a<str.length;a++)str[a]=str[a].charAt(0).toUpperCase()+str[a].slice(1);return str.join(" ")};function tag(a){return document.getElementById(a)}
function alert(a,b){tag("jade-alert")&&tag("jade-alert").remove();b||="System Message";const c=document.createElement("div");c.className="jade-alert";c.id="jade-alert";const d=document.createElement("div");d.className="jade-alert-header";d.innerHTML=b+'<div class="jade-alert-close"><i class="fas fa-times" style="color:white;margin-right:.3rem;cursor:pointer" onclick="this.parentNode.parentNode.parentNode.remove()"></div>';b=document.createElement("div");b.className="jade-alert-body";b.innerHTML=a;
c.appendChild(d);c.appendChild(b);document.body.appendChild(c)};
